# Generated by Django 4.2.5 on 2023-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_proj_img_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='img/content/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_img',
            field=models.ImageField(default=None, upload_to='img/title/'),
        ),
    ]
