# Generated by Django 4.2.5 on 2023-10-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_picture_image_alter_project_proj_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/content/"),
        ),
        migrations.AlterField(
            model_name="picture",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="app.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="proj_img",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="img/title/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="style",
            field=models.ManyToManyField(related_name="projects", to="app.style"),
        ),
    ]
